# Generated by Django 4.0.1 on 2022-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_link', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpotifyTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100, unique=True)),
                ('access_token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_token', models.CharField(max_length=100)),
                ('expires_in', models.DateTimeField()),
                ('token_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='SpotifyToken',
        ),
    ]
