# Generated by Django 4.0.1 on 2022-01-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_link', '0002_spotifytokens_delete_spotifytoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifytokens',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
