# Generated by Django 4.0.1 on 2022-01-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_link', '0004_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='vote',
        ),
    ]
